### ISSUE TITLE
Odd results

### ISSUE THREAD

**Issue by cm2435** [Lyz1213/CommitBart#1]
Hello! Im working on some similar things in git diff understanding. I tried to reproduce some simple examples with your model and was struggling; mind pointing out if there are any clear errors? 

Model loading code 
```
import torch
from transformers import PLBartForConditionalGeneration, PLBartTokenizer

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tokenizer = PLBartTokenizer.from_pretrained("NTU-CSL/CommitBART-base")
model = PLBartForConditionalGeneration.from_pretrained("NTU-CSL/CommitBART-base")
model.to(device)
```

Inference on a simple file
```
text = """[master (root-commit) 749055e] docs: Create README.md
1 file changed, 1 insertion(+)
create mode 100644 README.md"""

inputs = tokenizer(text, return_tensors="pt")

translated_tokens = model.generate(**inputs, decoder_start_token_id=tokenizer.lang_code_to_id["en_XX"])
tokenizer.batch_decode(translated_tokens, skip_special_tokens=True)[0]
```

yields an output of just
```
release release release release release release release release release release release release release release release release release release
```

Any help would be hugely appreciated!

**Comment by Lyz1213** [comment]
Hi, thanks for your interest. First of all, what we uploaded to Hugginface is a PLBART model, which doesn't include a generation head. If you want to use the model to do inference directly, you can load the lm_head.bin to the model.lm_head after initializing the pre-train model. Besides, the CommitBART-base needs token-type embedding. Thus I recommend you load CommitBART-uncase and load the corresponding lm_head.bin to do inference.

**Comment by workworkwc3** [comment]
Thank you for submitting the code to this very interesting paper. Similar to this original issue, I am also having trouble using the model for inference for security patch ID task on a custom dataset. I have reviewed the code for input and type processing (e.g., the "input_ids" and "type_ids" are already processed) based on 1) the explanation in the paper in section 4 (X = {[CLS][MSG]M[FILE]F[CODE]C} ), and 2) repository code. I too was hoping to use my processed data to run inference for security classification task using the models directly (i.e. no fine tuning), though I too am experiencing problems. 

I am trying to load the model from "ckpt" based on the code in ```run_patch.py:main()```. I have tried loading "pytorch_model.bin", "lm_head.bin", "module.bin", but with all - line 621 ```model.load_state_dict(torch.load(output_dir))``` experiences the following error (summarized): ```RuntimeError: Error(s) in loading state_dict for Bart_seq2seq:
        Missing key(s) in state_dict: ...
Unexpected key(s) in state_dict: "weight".```

Then I read and tried your suggestion to @cm2435. My understanding is that I can load CommitBART-base using huggingface API, use it to create a Bart_seq2seq class/model, and then load and assign the "lm_head.bin" to the lm_head attribute of the Bart_seq2seq class. This should let me perform direct inference right? To do this I again used code in ```run_patch.py:main()``` in the repository. Unfortunately I also experience an issue with the following code snippet (note all variables that aren't defined in this snippet are taken from earlier lines of the ```run_patch.py:main()``` file):

```
model = Bart_seq2seq(bart=model, config=config, args = args,
                    beam_size=args.beam_size, max_length=target_size,
                    sos_id=tokenizer.cls_token_id, eos_id=tokenizer.eos_token_id, type = True)
lm_head_path = "lm_head.bin"
lm_head = torch.load(output_dir, map_location=torch.device("cpu"))
model.lm_head.load_state_dict(lm_head)
```

The final line of the previous code snippet produces the following error:

```
*** RuntimeError: Error(s) in loading state_dict for Linear:
        size mismatch for weight: copying a param with shape torch.Size([50014, 768]) from checkpoint, the shape in current model is torch.Size([50015, 768]).
```

On inspecting the shape of model.lm_head and lm_head, it seems the size of their weights are truly off by one:

```
>>> lm_head['weight'].shape
torch.Size([50014, 768])
>>> model.lm_head.state_dict()['weight'].shape
torch.Size([50015, 768])
```

I am not sure if the code above is what you meant in your reply above, but I still find it produces some error as shown above. 

As two of us users are experiencing similar troubles related to model loading and direct inference, I am wondering if you plan to provide a file in this repository that displays an example for model loading for direct inference? I would argue a file with a complete pipeline for direct inference would be very beneficial for future users and researchers, as it would help them apply your model for direct inference for the same tasks with ease, and also fine tune your model further. 

As a high level outline, I personally believe a very beneficial and easy to understand file would:

1. Load the provided model (CommitBART-base variant) along with the LM head ready for direct inference
2. Define an example text, perhaps by sampling a single commit from your original dataset. Also describing the required columns that would be needed for users to plug in their own dataset would help. For example, columns: "repo", "commit_id", "diff", "msg", "filepath".
3. Process the data loaded in step 2 based on section 4 in the paper (generating "input_ids", "target_ids", "type_ids") and then create torch.utils.data.DataLoader by passing list of objects from your InputFeatures class. These functions would use the columns described in step 2 as well. 
4. Have the model predict on the Data/DataLoader from step 3, and process its output as needed (e.g. splitting "True"/"False" tokens.

**Comment by Lyz1213** [comment]
Thanks for your interest. We are sorry for the confusion. We want to declare that the model's lm_head file can be regarded as the lm_head of the PLBARTForConditionalGeneration model, which is trained from the pre-training stage. Loading the LM head can't help you to do the inference directly unless your input/output format is similar to the training objective we used in pre-training. If you want to do the patch identification, you still need to fine-tune it on your own.

For the error you encountered, we have checked the code and there is no such error when we run the code. The tokenizer size should be 50014, which consists of the original 50005 vocab plus the newly added 9 special tokens defined in  'new_word' in f_patch_data.py. Please check whether you have modified it. You can simply load and fine-tune the CommitBART-unseg model. The lm_head won't change the final results a lot.

Thanks for your suggestions, we would like to add these documents for further explanation in the future. For now, you can refer to the f_gen_data.py for the detailed data preprocessing process.
