### ISSUE TITLE
Missing key in provided data?

### ISSUE THREAD

**Issue by huichen-cs** [Lyz1213/CommitBart#2]
I appreciate it very much that you shared your code and data here, and the paper provides a lot of insights and interesting ideas.

I am looking into the classification task. I have a question. 

The code [here](https://github.com/Lyz1213/CommitBart/blob/6bbe324587b86fdbd4c601172a7efae416204eae/CommitBart/Classification/Security_patch_identification/data_preprocess/f_patch_data.py#L145) references a "vulnerable" key; however, none of the linked data file has this key. It also does not appear that there is another key indicating whether the patch is a vulnerable patch or not. 

Are the provided the data file for the generation task only? or the wrong data files were uploaded? or do I misunderstand anything here? Could you provide the data files with the "vulnerable" key? 

Thank you.

**Comment by Lyz1213** [comment]
Thanks for your interest. Now we have released our vulnerability detection data set

**Comment by huichen-cs** [comment]
@Lyz1213 

Thank you. I'll checked it out.
